#!/usr/bin/env python3
"""Turn brands_full.json into a JS catalog the app can search."""
import json, os, re, sys, random
sys.stdout.reconfigure(encoding="utf-8")

HERE = os.path.dirname(os.path.abspath(__file__))
brands = json.load(open(os.path.join(HERE, "brands_full.json"), encoding="utf-8"))

CUR = {"usd": "$", "gbp": "£", "eur": "€", "pln": "zł", "aud": "A$", "cad": "C$"}
CCY_BY_COUNTRY = {"USA": "$", "UK": "£", "Australia": "A$", "Canada": "C$",
                  "Japan": "¥", "Korea": "₩", "South Korea": "₩", "Poland": "zł"}

from import_brands import classify

# The generic HTML scraper sometimes grabs banners and template debris
# ("?goods status id=2", "ALL ITEMS SALE 30%OFF"). Better to show nothing
# for a brand than to show junk.
JUNK_PATTERNS = [
    r"^\?", r"status\s*id", r"goods\s*status", r"=\d", r"\bundefined\b", r"\bnull\b",
    r"^\W*$", r"^(shop|store|home|index|menu|cart|search|login|account|all)\b",
    r"\b(sale|off|discount|free shipping|new arrivals?|coming soon|lookbook|newsletter)\b",
    r"^\d+%", r"%\s*off", r"\.(jpg|png|webp|html?)$", r"^https?:",
    r"^(all items?|view all|see all|shop all|collection)\b",
]
JUNK_RE = re.compile("|".join(JUNK_PATTERNS), re.I)

def looks_like_product(title: str) -> bool:
    t = (title or "").strip()
    if len(t) < 3 or len(t) > 70:
        return False
    if JUNK_RE.search(t):
        return False
    letters = sum(ch.isalpha() for ch in t)
    if letters < 3 or letters / len(t) < 0.45:      # mostly symbols/numbers
        return False
    if len(t.split()) > 12:                          # a sentence, not a product
        return False
    return True

def cat_of(p, brand_kind="clothing"):
    s = f"{p['title']} {p.get('type','')} {p.get('tags','')}".lower()
    # products scraped from non-Shopify sites arrive unclassified
    if "kind" not in p:
        p["kind"] = classify(s, fallback=brand_kind)
    if p["kind"] == "art-decor": return "Art"
    if p["kind"] == "footwear":  return "Sneakers"
    if p["kind"] == "bags":      return "Bags"
    if re.search(r"jacket|coat|parka|vest|gilet|overshirt|blazer", s): return "Jackets"
    if re.search(r"hoodie|knit|sweater|jumper|cardigan|crewneck|fleece", s): return "Knitwear"
    if re.search(r"jean|denim|pant|trouser|short|cargo|sweatpant|jogger", s): return "Denim"
    if re.search(r"cap|hat|beanie|belt|sock|scarf|glove|balaclava|jewel|ring|necklace", s): return "Accessories"
    return "Tees"

def price_of(p, country):
    v = p.get("price")
    if not v: return None
    try: n = float(v)
    except (TypeError, ValueError): return None
    sym = CCY_BY_COUNTRY.get(country, "€")
    n = int(round(n))
    return f"{n} {sym}" if sym == "zł" else f"{sym}{n}"

def esc(s):
    return (s or "").replace("\\", "").replace('"', "'").strip()

catalog, brand_rows = [], []
pid = 1000
dropped = 0
for b in brands:
    brand_rows.append({
        "brand": esc(b["brand"]), "niche": esc(b["niche"]), "country": esc(b["country"]),
        "site": b.get("site"), "handle": b.get("handle"),
        "kind": b["kind"], "style": b["style"], "n": len(b["products"]),
    })
    for p in b["products"]:
        title = esc(p["title"])[:44]
        if not title or not p.get("image"): continue
        if not looks_like_product(title):
            dropped += 1
            continue
        pid += 1
        catalog.append({
            "id": pid, "brand": esc(b["brand"]), "name": title,
            "cat": cat_of(p, b["kind"]), "style": b["style"], "kind": p["kind"],
            "price": price_of(p, b["country"]), "indie": True,
            "src": b.get("handle") or ("@" + re.sub(r"[^a-z0-9]", "", b["brand"].lower())),
            "photo": p["image"], "link": p["url"],
            "likes": random.randint(80, 3200),
        })

# feed = a readable slice: max 3 items per brand, apparel first
random.seed(7)
by_brand = {}
for it in catalog:
    by_brand.setdefault(it["brand"], []).append(it)
feed = []
for items in by_brand.values():
    items.sort(key=lambda x: 0 if x["kind"] == "clothing" else 1)
    feed.extend(items[:3])
random.shuffle(feed)
feed_ids = [i["id"] for i in feed[:120]]

out = os.path.join(HERE, "assets", "js")
os.makedirs(out, exist_ok=True)
with open(os.path.join(out, "catalog.js"), "w", encoding="utf-8") as f:
    f.write("/* generated by build_app_data.py — do not edit by hand */\n")
    f.write("const BRANDS=" + json.dumps(brand_rows, ensure_ascii=False, separators=(",", ":")) + ";\n")
    f.write("const CATALOG=" + json.dumps(catalog, ensure_ascii=False, separators=(",", ":")) + ";\n")
    f.write("const FEED_IDS=" + json.dumps(feed_ids, separators=(",", ":")) + ";\n")

kinds = {}
for it in catalog: kinds[it["kind"]] = kinds.get(it["kind"], 0) + 1
cats = {}
for it in catalog: cats[it["cat"]] = cats.get(it["cat"], 0) + 1
size = os.path.getsize(os.path.join(out, "catalog.js")) // 1024
print(f"junk dropped: {dropped}")
print(f"brands   : {len(brand_rows)}")
print(f"products : {len(catalog)}  (feed shows {len(feed_ids)})")
print(f"kinds    : {kinds}")
print(f"categories: {cats}")
print(f"-> assets/js/catalog.js  ({size} KB)")
